### ISSUE TITLE
Running game glitches when user switches between gameplay screen and scene

### ISSUE THREAD

**Issue by MahimaChawla** [Dan-Bai/MonsterPass#23]
While the game is running, if a user switches to the 'scene' tab, and then goes back to the 'gameplay' tab, the game goes to a still image of the background and does not display any other components. The game is still running in this scenario. A similar glitch occurs when the game is left open for a couple of hours, or if the laptop is put to sleep and reponed. This might be a session issue. To recreate, please shift between tabs, or leave the application running while interacting with other applications.

**Comment by MahimaChawla** [comment]
This is an enhancement level issue.

**Comment by Dan-Bai** [comment]
Please be advised. Only items in the Play view show up on mobile, everything else is only for developers in Unity.
